services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    environment:
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_USER: user1
      # CLICKHOUSE_DB: mydb 
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP интерфейс ClickHouse
      - "9000:9000"  # Native TCP интерфейс ClickHouse
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse   # Директория для хранения данных
    networks:
      - mynetwork                   # Подключаем контейнер к сети
    restart: always                 # Автоматический перезапуск контейнера

networks:
  mynetwork:
    driver: bridge
